tasks:
  - init: |
      export ROOTDIR=$(pwd)
      cd apps/backend && npm install && npm run start
  - command:      
      cd apps/storefront && yarn install --mutex network:31999 && yarn dev
  - command:
      cd apps/admin && yarn install --mutex network:31999 && yarn start